### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.compat'

### ISSUE THREAD

**Issue by amalmathew7** [otuva/handwriting-synthesis#11]
having error ModuleNotFoundError: No module named 'tensorflow.compat' when I try to run main.py
Traceback (most recent call last):
  File "C:\Users\Amal\Documents\handwriting-synthesis\main.py", line 2, in <module>
    from handwriting_synthesis import Hand
  File "C:\Users\Amal\Documents\handwriting-synthesis\handwriting_synthesis\__init__.py", line 3, in <module>
    from .hand import Hand
  File "C:\Users\Amal\Documents\handwriting-synthesis\handwriting_synthesis\hand\__init__.py", line 1, in <module>
    from .Hand import Hand
  File "C:\Users\Amal\Documents\handwriting-synthesis\handwriting_synthesis\hand\Hand.py", line 9, in <module>
    from handwriting_synthesis.rnn import RNN
  File "C:\Users\Amal\Documents\handwriting-synthesis\handwriting_synthesis\rnn\__init__.py", line 1, in <module>
    from .LSTMAttentionCell import LSTMAttentionCell
  File "C:\Users\Amal\Documents\handwriting-synthesis\handwriting_synthesis\rnn\LSTMAttentionCell.py", line 5, in <module>
    import tensorflow.compat.v1 as tfcompat
ModuleNotFoundError: No module named 'tensorflow.compat'

Process finished with exit code 1

**Comment by otuva** [comment]
Hi, did you install according to the [instructions](https://github.com/otuva/handwriting-synthesis#installation)
