### ISSUE TITLE
Error when trying to Train

### ISSUE THREAD

**Issue by GorillaDetective** [otuva/handwriting-synthesis#8]
Hi! Thanks for porting this over to tensorflow 2.x 

When I try to run the training function I get the following errors:

>>> from handwriting_synthesis.training import train
>>> train()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path_to_script>\train.py", line 7, in train
    dr = DataReader(data_dir=<path_to_processed_data>)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path_to_script>\DataReader.py", line 20, in __init__
    self.train_df, self.val_df = self.test_df.train_test_split(train_size=0.95, random_state=2018)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path_to_script>\DataFrame.py", line 42, in train_test_split
    train_idx, test_idx = train_test_split(
                          ^^^^^^^^^^^^^^^^^
  File "<path_to_python_library>\_split.py", line 2562, in train_test_split
    n_train, n_test = _validate_shuffle_split(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path_to_python_library>\_split.py", line 2236, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=None and train_size=0.95, the resulting train set will be empty. Adjust any of the aforementioned parameters.
>>>

**Comment by GorillaDetective** [comment]
Hi @otuva !

Thanks for the quick reply! Confirming I have prepared the data. I was originally following the instructions in the readme file:

To train the model, run 

```python
from handwriting_synthesis.training import train
train()
```

This takes a couple of days on a single Tesla K80.

but now that you pointed out that I need to run this from main.py, I went back and tried that. I received the following similar errors:

<PATH_TO_HANDWRITING_SYNTHESIS_FOLDER>\python main.py
WARNING:tensorflow:From <PYTHON_LIB_PATH>\tensorflow\python\compat\v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
traversing data directory...
0 model\data\raw\ascii\forms.txt
1 model\data\raw\ascii\lines.txt
2 model\data\raw\ascii\sentences.txt
3 model\data\raw\ascii\words.txt
dumping to numpy arrays...
Traceback (most recent call last):
  File "<PATH_TO_HANDWRITING_SYNTHESIS_FOLDER>\main.py", line 32, in <module>
    train()
  File "<PATH_TO_HANDWRITING_SYNTHESIS_FOLDER>\handwriting_synthesis\training\train.py", line 7, in train
    dr = DataReader(data_dir=processed_data_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PATH_TO_HANDWRITING_SYNTHESIS_FOLDER>\handwriting_synthesis\training\DataReader.py", line 20, in __init__
    self.train_df, self.val_df = self.test_df.train_test_split(train_size=0.95, random_state=2018)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PYTHON_LIB_PATH>\sklearn\model_selection\_split.py", line 2562, in train_test_split
    n_train, n_test = _validate_shuffle_split(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<PYTHON_LIB_PATH>\sklearn\model_selection\_split.py", line 2236, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=None and train_size=0.95, the resulting train set will be empty. Adjust any of the aforementioned parameters.

Looks like it's the same error. I am probably doing something wrong. Let me know if you need more info!

Thanks!

**Comment by otuva** [comment]
@GorillaDetective You are using windows right, because I was unable to reproduce the issue with multiple machines

I was going to publish docker image after publishing to pypi package but if you'd like I can share a Dockerfile pulling from this repo

**Comment by GorillaDetective** [comment]
@otuva 

Thanks for the response! Yes I am using windows, a Dockerfile would be great, thanks!

**Comment by otuva** [comment]
@GorillaDetective there you go https://github.com/otuva/hw-synthesis-docker

**Comment by GorillaDetective** [comment]
@otuva Thanks!!

I am sad to say I am still getting the same error though:

t_gra@DESKTOP-J3G03C3 MINGW64 ~/handwriting-synthesis/hw-synthesis-docker (master)
$ docker-compose build
#1 [handwriting internal] load build definition from Dockerfile
#1 transferring dockerfile: 629B done
#1 DONE 0.0s

#2 [handwriting internal] load .dockerignore
#2 transferring context: 2B done
#2 DONE 0.0s

#3 [handwriting internal] load metadata for docker.io/library/python:3.11.3-slim-buster
#3 DONE 0.4s

#4 [handwriting 1/6] FROM docker.io/library/python:3.11.3-slim-buster@sha256:9861d22af8ed68875e59a4187c0b99aa03e01aaf82f565e9548ec3c3fc2a325e
#4 DONE 0.0s

#5 [handwriting 2/6] RUN apt update && apt install -y git
#5 CACHED

#6 [handwriting 3/6] WORKDIR /app
#6 CACHED

#7 [handwriting 4/6] RUN git clone 'https://github.com/otuva/handwriting-synthesis' .
#7 CACHED

#8 [handwriting 5/6] RUN pip install -r requirements.txt
#8 CACHED

#9 [handwriting 6/6] RUN rm main.py
#9 CACHED

#10 [handwriting] exporting to image
#10 exporting layers done
#10 writing image sha256:8ec62601fd198bca21d977534b6b36eb32150c49fa7636debdd09ed475713c32 done
#10 naming to docker.io/library/hw-synthesis-docker-handwriting done
#10 DONE 0.0s

t_gra@DESKTOP-J3G03C3 MINGW64 ~/handwriting-synthesis/hw-synthesis-docker (master)
$ docker-compose run --rm handwriting
2023-06-02 02:57:08.963375: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-02 02:57:08.999814: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-02 02:57:09.000244: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-02 02:57:09.773533: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /usr/local/lib/python3.11/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
press enter to prepare. type 'skip' to skip

traversing data directory...
dumping to numpy arrays...
press enter to train. type 'skip' to skip

Traceback (most recent call last):
  File "/app/main.py", line 9, in <module>
    print("skipped") if cho1 == "skip" else train()
                                            ^^^^^^^
  File "/app/handwriting_synthesis/training/train.py", line 7, in train
    dr = DataReader(data_dir=processed_data_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/handwriting_synthesis/training/DataReader.py", line 20, in __init__
    self.train_df, self.val_df = self.test_df.train_test_split(train_size=0.95, random_state=2018)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/handwriting_synthesis/data_frame/DataFrame.py", line 42, in train_test_split
    train_idx, test_idx = train_test_split(
                          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2562, in train_test_split
    n_train, n_test = _validate_shuffle_split(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sklearn/model_selection/_split.py", line 2236, in _validate_shuffle_split
    raise ValueError(
ValueError: With n_samples=0, test_size=None and train_size=0.95, the resulting train set will be empty. Adjust any of the aforementioned parameters.

**Comment by GorillaDetective** [comment]
It appears the created files in the processed folder are all empty. example:

t_gra@DESKTOP-J3G03C3 MINGW64 ~/handwriting-synthesis/hw-synthesis-docker (master)
$ cat model/data/processed/c.npy
▒NUMPYv{'descr': '|i1', 'fortran_order': False, 'shape': (0, 75), }

**Comment by otuva** [comment]
The error you have posted stems from the fact that required directories are not there, hence my first question

> Have you prepared the data

You can't prepare something non-existent :)

It's not your fault, I'll make sure to add checks 

For now, though, can you follow [these instructions](https://github.com/otuva/handwriting-synthesis/tree/master/model) to put required files under `raw`? 

(make sure to extract `tar.gz` files. you might need 7zip for windows)

**Comment by GorillaDetective** [comment]
HI @otuva,

Thanks for this! I redownloaded all the files (using the links you provided [here](https://github.com/otuva/handwriting-synthesis/tree/master/model) ) and removed any of the old files and removed the empty files that had been prepared previously. I also confirmed that these new raw data files are present in the correct 'model/data/raw' folder.

When I try to run the program now, I get an error where is looks like it is looking for a non existent file:

t_gra@DESKTOP-J3G03C3 MINGW64 ~/handwriting-synthesis/hw-synthesis-docker (master)
$ docker-compose run --rm handwriting
2023-06-02 13:40:39.770460: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-02 13:40:39.815270: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-02 13:40:39.815713: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-02 13:40:40.629966: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /usr/local/lib/python3.11/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
press enter to prepare. type 'skip' to skip

Traceback (most recent call last):
  File "/app/main.py", line 6, in <module>
traversing data directory...
0 model/data/raw/ascii/a01/a01-000/a01-000u.txt
    print("skipped") if cho1 == "skip" else prepare()
                                            ^^^^^^^^^
  File "/app/handwriting_synthesis/training/preparation/prepare.py", line 14, in prepare
    stroke_fnames, transcriptions, writer_ids = collect_data()
                                                ^^^^^^^^^^^^^^
  File "/app/handwriting_synthesis/training/preparation/operations.py", line 80, in collect_data
    tree = ElementTree.parse(original_xml)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 1218, in parse
    tree.parse(source, parser)
  File "/usr/local/lib/python3.11/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
             ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'model/data/raw/original/a01/a01-000/strokesu.xml'

I double checked the 'origainl-xml-part.tar,gz' file and there is no 'original/a01/a01-000/strokesu.xml' file present. But there is a 'original/a01/a01-001/strokesu.xml' file...  

Appreciate all your help!

**Comment by MJT0** [comment]
Did you ever figure this part out? currently im having the same training error

"FileNotFoundError: [Errno 2] No such file or directory: 'model/data/raw/original/a01/a01-000/strokesu.xml'"

When checking the file paths, that file does not exist. i tried renaming files and even adding files but It would just keep happening with other files in the training path that didn't exist.

I think for some reason the code is set to go in some chronological order looking for files in the preparing process but does not know what to do when the file is not there.

**Comment by bryandam** [comment]
@MJT0: You need to download the IAM On-Line Handwriting Database and extract it into the raw folder: https://fki.tic.heia-fr.ch/databases/iam-on-line-handwriting-database

I checked and the file you list above exists in the dataset.

**Comment by ShinToWin** [comment]
Bryan, I took your advice and extracted all the IAM-Online files into the raw folder. I had the same issues as Gorilla, but when using your advice above I get a step father. Worthy to note I am using the files
- ascii-all.tar
-  lineImages-all.tar
-  lineStrokes-all.tar
- original-xml-all.tar
(these files extracted into the raw folder are no longer compressed zip files)

When preparing the data, I get progress with lines such as "1900 model\data\raw\ascii\z01\z01-000\z01-000.txt

However, after that line it gives me the error of:

training\preparation\operations.py", line 90, in collect_data
    assert len(ascii_sequences) == len(line_stroke_fnames)
AssertionError

Concluding the preparation is incomplete, and something is wrong. Any advice? Thanks.

**Comment by ShinToWin** [comment]
> @MJT0: You need to download the IAM On-Line Handwriting Database and extract it into the raw folder: https://fki.tic.heia-fr.ch/databases/iam-on-line-handwriting-database
> 
> I checked and the file you list above exists in the dataset.

Bryan, I took your advice and extracted all the IAM-Online files into the raw folder. I had the same issues as Gorilla, but when using your advice above I get a step father. Worthy to note I am using the files

ascii-all.tar
lineImages-all.tar
lineStrokes-all.tar
original-xml-all.tar
(these files extracted into the raw folder are no longer compressed zip files)
When preparing the data, I get progress with lines such as "1900 model\data\raw\ascii\z01\z01-000\z01-000.txt

However, after that line it gives me the error of:

training\preparation\operations.py", line 90, in collect_data
assert len(ascii_sequences) == len(line_stroke_fnames)
AssertionError

Concluding the preparation is incomplete, and something is wrong. Any advice? Thanks.

**Comment by sah1lga1kwad** [comment]
Can anybody tell me how can I use my own handwriting? Like I give it data of my own handwriting and it outputs in that style? Is it possible? how much data will be required for significant output? Please guide me.
